name: Build Electron App

on:
  push:
    branches: [ main, master, feature/* ]

# Default permissions are read-only
permissions: {}

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          
      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: |
          npm run clean
          npx electron-builder --publish never
        env:
          USE_HARD_LINKS: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v7
        with:
          name: windows-artifacts
          path: dist/**/*.exe

      - name: Upload macOS artifacts
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v7
        with:
          name: macos-artifacts
          path: dist/**/*.dmg

      - name: Upload Linux artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v7
        with:
          name: linux-artifacts
          path: dist/**/*.AppImage
